### ISSUE TITLE
OpenBSD Parse error

### ISSUE THREAD

**Issue by delvin-fil** [polachok/skb#3]
sudo make
*** Parse error in /home/delvin/distr/skb: Missing dependency operator (Makefile:3)
*** Parse error: Missing dependency operator (config.mk:3)
*** Parse error: Missing dependency operator (config.mk:5)
*** Parse error: Missing dependency operator (config.mk:9)
*** Parse error: Missing dependency operator (config.mk:12)
*** Parse error: Missing dependency operator (config.mk:16)
*** Parse error: Missing dependency operator (config.mk:22)
*** Parse error: Missing dependency operator (config.mk:27)
*** Parse error: Missing dependency operator (Makefile:5)
*** Parse error: Missing dependency operator (Makefile:10)
*** Parse error: Missing dependency operator (Makefile:12)
*** Parse error: Missing dependency operator (Makefile:19)
*** Parse error: Missing dependency operator (Makefile:23)
*** Parse error: Missing dependency operator (Makefile:28)
*** Parse error: Missing dependency operator (Makefile:33)
*** Parse error: Missing dependency operator (Makefile:37)
*** Parse error: Missing dependency operator (Makefile:46)
*** Parse error: Missing dependency operator (Makefile:52)

**Comment by polachok** [comment]
try sudo gmake

**Comment by delvin-fil** [comment]
Thanks, solved.
